Repository codestates-seb/seb41_main_027, pull requests merged in 2023-02, with the labels that each got.

#266 🔨 chore : style 고도화
  client/src/components/Map/MainMap.js
  client/src/pages/AboutUs/AboutUs.js
  client/src/pages/Mypage/MyInfoStyle.js
  client/src/pages/Mypage/Mypage.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#267 🔨 chore : 서비스 소개 크루들의 한마디 추가
  client/src/pages/AboutUs/AboutUs.js
  client/src/pages/AboutUs/TabAboutUs.js
Labels: ☀️ FE

#268 🔨 chore : 서비스소개 및 UI style 고도화
  client/src/components/Map/MainMap.js
  client/src/pages/AboutUs/AboutUs.js
  client/src/pages/AboutUs/TabAboutUs.js
  client/src/pages/Mypage/MyInfoStyle.js
  client/src/pages/Mypage/Mypage.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 🎨 리팩토링

#269 💄 style : style 고도화 (사용성 관련 수정)
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#270 🔨 chore : radioButton 버그 수정
  client/src/components/Map/SearchBar/RadioButton.js
Labels: ☀️ FE, 🔧 버그 수정

#271 🔨 chore : 장소상세모달 버그 수정 외
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/TitleStyle.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Nav/Nav.js
  client/src/hooks/useLoginCheck.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/query/place.js
  client/src/query/review.js
  client/src/recoil/modalState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/common.js
Labels: ☀️ FE, 🔧 버그 수정, 💄 스타일, 🔨 수정

#272 👷 build : 자잘한 버그 수정 완료버전
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/TitleStyle.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Nav/Nav.js
  client/src/hooks/useLoginCheck.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/query/place.js
  client/src/query/review.js
  client/src/recoil/modalState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/common.js
Labels: ☀️ FE, 👷 빌드 수정, 🚚 배포 관련

#274 🔨 chore: admin 권한 페이지 라우터 수정
  client/src/App.js
  client/src/components/Map/MainMap copy.js
Labels: ☀️ FE, 🔧 버그 수정
