Repository codestates-seb/seb41_main_027, pull requests merged in 2023-01, with the labels that each got.

#15 feat : user entity, controller, dto 생성
  server/src/main/java/main027/server/domain/user/controller/UserController.java
  server/src/main/java/main027/server/domain/user/dto/UserDto.java
  server/src/main/java/main027/server/domain/user/entity/User.java
  server/src/main/java/main027/server/domain/user/user.java
Labels: 🌕 BE, 💡 새기능

#16 feat: BaseTime, Review Entity, Dto 생성
  server/src/main/java/main027/server/domain/audit/BaseTime.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
  server/src/main/java/main027/server/domain/review/review.java
  server/src/main/java/main027/server/global/Basic.java
  server/src/main/resources/application-sh.properties
Labels: 🌕 BE, 💡 새기능

#18 🔨 chore : Place Entity 의존 관계 수정
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
Labels: 🌕 BE, 🔨 수정

#19 chore : user -> member로 이름 변경
  server/src/main/java/main027/server/domain/user/controller/MemberController.java
  server/src/main/java/main027/server/domain/user/controller/UserController.java
  server/src/main/java/main027/server/domain/user/dto/MemberDto.java
  server/src/main/java/main027/server/domain/user/dto/UserDto.java
  server/src/main/java/main027/server/domain/user/entity/Member.java
  server/src/main/java/main027/server/domain/user/entity/User.java
  server/src/test/java/main027/server/domain/user/controller/MemberControllerTest.java
Labels: 🌕 BE, 🔨 수정

#21 chore, test: Review 도메인 User -> Member 수정, 테스트코드 추가
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
  server/src/test/java/main027/server/domain/review/repository/ReviewRepositoryTest.java
Labels: 🌕 BE, ✅ 테스트, 🔨 수정

#23 test : MemberControllerTest 작성
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
Labels: 🌕 BE, ✅ 테스트

#24 chore : Dto 유효성 검증 로직 추가, Controller Test 수정
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
Labels: 🌕 BE, 🔨 수정

#29 ✅ test : PlaceControllerTest 작성
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/test/java/main027/server/domain/PlaceTest/PlaceControllerTest.java
Labels: 🌕 BE, ✅ 테스트

#39 chore : deploy.sh 수정2
  server/scripts/deploy.sh
Labels: 🌕 BE, 📝 문서 관련

#40 docs : deploy.sh 수정3
  server/scripts/deploy.sh
Labels: 🌕 BE, 📝 문서 관련

#41 docs : deploy.sh 수정4
  server/scripts/deploy.sh
Labels: 🌕 BE, 📝 문서 관련

#42 docs : deploy.sh 수정4
  server/scripts/deploy.sh
Labels: 🌕 BE, 📝 문서 관련

#49 chore : Member 엔티티 컨트롤러 dto 수정
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/entity/Member.java
  server/src/main/java/main027/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/main027/server/domain/member/repository/MemberRepository.java
  server/src/main/java/main027/server/domain/member/service/MemberService.java
Labels: 🌕 BE, 🔨 수정

#51 ✨ feat : PlaceService / PlaceMapper / PlaceRepository 구현
  server/src/main/generated/main027/server/domain/member/mapper/MemberMapperImpl.java
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 💡 새기능

#56 category, 장소투표 매핑
  server/src/main/java/main027/server/domain/place/entity/Category.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/entity/PlaceLikeUser.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
Labels: 🌕 BE, 💡 새기능

#62 ✨ feat : 북마크 등록 기본 코드 작성 완료
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkService.java
Labels: 🌕 BE, 💡 새기능

#63 ✨ feat : Place Service 내 Create / Delelte 검증 로직 추가
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
Labels: 🌕 BE, 💡 새기능

#64 🔨 chore : properties, bookmark 자잘한 수정입니다.
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkService.java
  server/src/test/resources/application-jpaLog.properties
  server/src/test/resources/application-test.properties
Labels: 🌕 BE, 👷 빌드 수정, 📝 문서 관련

#69 👷 build : npm package install set up
  client/.eslintrc
  client/.gitignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
Labels: ☀️ FE, 👷 빌드 수정

#68 🎨 refactor : 코드 리팩토링 및 검증 추가
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkService.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/service/EmojiService.java
  server/src/main/java/main027/server/domain/review/service/ReviewService.java
Labels: 🌕 BE, 🎨 리팩토링

#70 🔨 chore : Tag 기능 삭제
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
Labels: 🌕 BE, 🔨 수정

#71 ✅ test : bookmark service 테스트 코드
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceSliceTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
Labels: 🌕 BE, ✅ 테스트

#73 ✨ feat : 공통 Layout Set up
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Map/Map.js
  client/src/components/Nav/Nav.js
  client/src/components/Nav/images/Logo.svg
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#77 ✨ feat : recoil, axios 기본 셋팅
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/api/bookmark.js
  client/src/api/member.js
  client/src/api/place.js
  client/src/api/review.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/Place.js
  client/src/utils/ScrollToTop.js
Labels: ☀️ FE, 💄 스타일

#78 bookmark 서비스, 리포지토리 구현건입니다.
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkService.java
  server/src/main/resources/application-sh.properties
Labels: 🌕 BE, 💡 새기능

#79 ✨ feat : BookMark Dto 관련 코드 추가
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
Labels: 🌕 BE, 💡 새기능

#81 BM repo 테스트 코드 추가 및 설정 수정
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/resources/application-sh.properties
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/resources/application-test.properties
  server/src/test/resources/sql/data.sql
Labels: 🌕 BE, ✅ 테스트, 📝 문서 관련

#84 ✅ test : BM 테스트코드 작성
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceSliceTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
Labels: 🌕 BE, ✅ 테스트

#85 ✅ test : Review 테스트 추가
  server/src/main/java/main027/server/domain/review/service/ReviewService.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/main027/server/domain/review/repository/ReviewRepositoryTest.java
  server/src/test/java/main027/server/domain/review/service/ReviewServiceSliceTest.java
Labels: 🌕 BE, ✅ 테스트

#94 🎨 refactor : Review, Bookmark 리팩토링
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkService.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/service/ReviewService.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/domain/review/verifier/EmojiVerifier.java
  server/src/main/java/main027/server/domain/review/verifier/ReviewVerifier.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceSliceTest.java
  server/src/test/java/main027/server/domain/review/service/ReviewServiceSliceTest.java
Labels: 🌕 BE, 🎨 리팩토링

#95 refactor : MemberService 리팩토링
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/service/MemberService.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateService.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
Labels: 🌕 BE, 🎨 리팩토링

#98 🎨 refactor : 전체 코드 리팩토링
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/domain/place/verifier/PlaceVerifier.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/domain/review/verifier/ReviewVerifier.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceSliceTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/service/ReviewServiceSliceTest.java
Labels: 🌕 BE, 🎨 리팩토링

#99 ✨ feat : SearchBar
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Map/Map.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/components/Nav/Nav.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💡 새기능, 💄 스타일

#102 📝 docs : update gitignore
  .gitignore
Labels: 🌕 BE, 📝 문서 관련

#103 ✨ feat : maps
  client/src/App.js
  client/src/components/Map/Map.js
  client/src/pages/Home.js
Labels: ☀️ FE, 💡 새기능

#106 🔨 chore : 파일 통합 재 배포용
  client/.eslintrc
  client/src/components/Map/Map.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/pages/Home.js
Labels: ☀️ FE

#111 🔨 chore : SearchBar Style 수정
  client/src/components/Map/SearchBar/SearchBar.js
Labels: ☀️ FE, 💄 스타일, 🔨 수정

#112 🔨 chore : 전역 스타일링 Toast root 스타일링 추가
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#113 📝 docs : yml 수정, stubdata 추가
  server/src/main/resources/application.yml
  server/src/main/resources/sql/data.sql
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
  server/src/test/resources/application.yml
  server/src/test/resources/sql/data.sql
Labels: 🌕 BE, 💡 새기능

#114 feat : JWT 자격증명을 위한 로그인 인증 구현 1
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/entity/Member.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
Labels: 🌕 BE, 💡 새기능

#116 🔨 chore : CI변경 및 Nav Link 연결
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Map/Map.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Nav/Nav.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#118 properties 삭제 및 코드 자잘한 수정
  server/src/main/resources/application-jm.properties
  server/src/main/resources/application-sh.properties
  server/src/main/resources/application.properties
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/main027/server/domain/review/repository/ReviewRepositoryTest.java
  server/src/test/resources/application-jpaLog.properties
  server/src/test/resources/application-test.properties
  server/src/test/resources/application.properties
Labels: 🌕 BE, 🎨 리팩토링, 📝 문서 관련

#117 💄 style : CI Logo 위치 조정
  client/src/components/Nav/Nav.js
Labels: ☀️ FE, 💄 스타일

#121 🔨 chore : Layout Elevation 조정
  client/src/components/Header/Header.js
  client/src/components/Map/Map.js
  client/src/components/Nav/Nav.js
  client/src/styles/GlobalStyle.js
Labels: ☀️ FE, 💄 스타일

#122 stubdata, bookmark test 코드 수정
  server/src/main/resources/sql/data.sql
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
  server/src/test/java/main027/server/domain/review/service/ReviewServiceSliceTest.java
  server/src/test/resources/sql/data.sql
Labels: 🌕 BE, 🔨 수정, 📝 문서 관련

#123 ✨ feat : SiteInfoCard
  client/src/components/Map/Map.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
Labels: ☀️ FE, 💡 새기능, 💄 스타일

#124 ✨ feat : 리뷰 리스트 페이징 처리 구현
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewService.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/resources/application.yml
  server/src/test/java/main027/server/domain/review/repository/ReviewRepositoryTest.java
  server/src/test/java/main027/server/domain/review/service/ReviewServiceSliceTest.java
Labels: 🌕 BE, 💡 새기능, ✅ 테스트

#126 feat : JWT 자격 증명을 위한 로그인 인증 구현 2
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
Labels: 🌕 BE, 💡 새기능

#128 ✨ feat: 기본 기능 추가
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/api/bookmark.js
  client/src/api/member.js
  client/src/api/place.js
  client/src/api/review.js
  client/src/components/Loading/Loading.js
  client/src/hooks/useFetch.js
  client/src/hooks/useToastPopup.js
  client/src/pages/NotFound.js
  client/src/store/state/toastPopupState.js
Labels: ☀️ FE, 💡 새기능, 🚚 배포 관련

#129 ✅ test: 배포 테스트
  client/src/api/bookmark.js
  client/src/api/member.js
  client/src/api/place.js
  client/src/api/review.js
  client/src/pages/Mypage.js
Labels: ☀️ FE, 🚚 배포 관련

#140 JWT를 이용한 자격 증명 및 검증 구현과 MemberController JWT 제외
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
Labels: 🌕 BE, 💡 새기능, ✅ 테스트

#145 👷 build : 배포테스트
  .github/workflows/client.yml
Labels: ☀️ FE, 🚚 배포 관련

#151 ✅ test : build test
  .github/workflows/client-test.yml
  .github/workflows/client.yml
  client/README.md
Labels: ✅ 테스트, 🚚 배포 관련

#152 feat : redis 추가 & config 클래스 생성
  server/build.gradle
  server/src/main/java/main027/server/global/config/RedisConfig.java
Labels: 🌕 BE, 💡 새기능, 📝 문서 관련

#154 chore : JWT 관련 클래스 주석 추가
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
Labels: 🌕 BE, 🔨 수정

#157 ✨ feat : PlaceLike 기능 구현 및 Test Code 주석 처리
  server/src/docs/asciidoc/index.adoc
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/entity/PlaceLikeUser.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceLikeUserMapper.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeService.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTestJM.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
Labels: 🌕 BE, 💡 새기능, ✅ 테스트, 📝 문서 관련

#158 ✨ feat : 회원가입 구현
  client/src/api/sign.js
  client/src/assets/Logo.svg
  client/src/assets/LogoTypeSignature.svg
  client/src/components/Sign/Register.js
  client/src/pages/SignIn.js
  client/src/pages/SignUp.js
Labels: ☀️ FE, 💡 새기능

#159 🔨 chore : entity Lazy 옵션 추가
  .github/workflows/client.yml
  server/README.md
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
Labels: 🌕 BE, 🔨 수정

#160 ✨ feat : logging 기능 추가
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/global/aop/logging/LogStopWatch.java
  server/src/main/java/main027/server/global/aop/logging/annotation/TimeTrace.java
  server/src/main/java/main027/server/global/aop/logging/annotation/isInitial.java
  server/src/main/java/main027/server/global/aop/logging/aspect/TimeTraceAspect.java
  server/src/main/resources/application.yml
Labels: 🌕 BE, 💡 새기능

#161 📝 docs : Review Bookmark Javadoc 추가
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/entity/Emoji.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/global/aop/logging/LogStopWatch.java
  server/src/main/java/main027/server/global/aop/logging/annotation/TimeTrace.java
  server/src/main/java/main027/server/global/aop/logging/annotation/isInitial.java
  server/src/main/java/main027/server/global/aop/logging/aspect/TimeTraceAspect.java
  server/src/main/java/main027/server/global/audit/BaseTime.java
Labels: 🌕 BE, 📝 문서 관련

#163 테스트 코드 변경, 설정 변경
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/test/java/main027/server/global/logging/TimeTraceTest.java
  server/src/test/resources/application.yml
Labels: 🌕 BE, 🔨 수정, 📝 문서 관련

#164 Backend
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/entity/PlaceLikeUser.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceLikeUserMapper.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeService.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/entity/Emoji.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/global/aop/logging/LogStopWatch.java
  server/src/main/java/main027/server/global/aop/logging/annotation/TimeTrace.java
  server/src/main/java/main027/server/global/aop/logging/annotation/isInitial.java
  server/src/main/java/main027/server/global/aop/logging/aspect/TimeTraceAspect.java
  server/src/main/java/main027/server/global/audit/BaseTime.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/main027/server/global/config/RedisConfig.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTestJM.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/main027/server/global/logging/TimeTraceTest.java
  server/src/test/resources/application.yml
Labels: 🌕 BE

#165 ✨ feat : Place Like Count 기능 구현 및 테스트 완료
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/repository/MemberRepository.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/PlaceLikeUser.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateServiceImpl.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTestJM.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
Labels: 🌕 BE, 💡 새기능, ✅ 테스트

#166 mapper, 컨트롤러 리팩토링
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/resources/sql/data.sql
Labels: 🌕 BE, 🎨 리팩토링

#167 🔨 chore : Review @TimeTrace 추가
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
Labels: 🌕 BE, 🔨 수정

#168 🔨 chore : 패키지 구조 변경
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/verifier/PlaceVerifier.java
  server/src/main/java/main027/server/domain/review/verifier/EmojiVerifier.java
  server/src/main/java/main027/server/domain/review/verifier/ReviewVerifier.java
  server/src/main/java/main027/server/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/main027/server/global/advice/dto/ErrorResponse.java
  server/src/main/java/main027/server/global/advice/exception/BusinessLogicException.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/main/java/main027/server/global/aop/logging/annotation/TimeTrace.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/resources/application.yml
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 🔨 수정

#169 ✨ feat : Place List 조회 기능 추가
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/repository/MemberRepository.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/PlaceLikeUser.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/place/verifier/PlaceVerifier.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/domain/review/verifier/EmojiVerifier.java
  server/src/main/java/main027/server/domain/review/verifier/ReviewVerifier.java
  server/src/main/java/main027/server/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/main027/server/global/advice/dto/ErrorResponse.java
  server/src/main/java/main027/server/global/advice/exception/BusinessLogicException.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/main/java/main027/server/global/aop/logging/annotation/TimeTrace.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/resources/application.yml
  server/src/main/resources/sql/data.sql
  server/src/main/resources/static/docs/index.html
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTestJM.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
Labels: 🌕 BE, 💡 새기능, ✅ 테스트

#174 Merge to backend
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/main/java/main027/server/global/aop/logging/MemberHolder.java
  server/src/main/java/main027/server/global/auth/Redis/RedisConfiguration.java
  server/src/main/java/main027/server/global/auth/Redis/RedisService.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtReissueFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/config/RedisConfig.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/index.html
Labels: 🌕 BE, 💡 새기능, 🔨 수정, 🎨 리팩토링, 📝 문서 관련

#176 🔨 chore : 컨트롤러 api 통합 및 isliked, isBookmarked 추가
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/place/controller/LikeController.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeService.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/global/aop/logging/LogStopWatch.java
  server/src/main/resources/sql/data.sql
Labels: 🌕 BE, 💡 새기능, 🔨 수정

#177 ➖ minus : import 제거
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/bookmark/mapper/BookmarkMapper.java
  server/src/main/java/main027/server/domain/bookmark/repository/BookmarkRepository.java
  server/src/main/java/main027/server/domain/bookmark/service/BookmarkServiceImpl.java
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/entity/Member.java
  server/src/main/java/main027/server/domain/member/mapper/MemberMapper.java
  server/src/main/java/main027/server/domain/member/service/MemberService.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/place/controller/LikeController.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceLikeUserMapper.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/dto/ReviewDto.java
  server/src/main/java/main027/server/domain/review/entity/Review.java
  server/src/main/java/main027/server/domain/review/mapper/ReviewMapper.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
Labels: 🌕 BE, 💄 스타일

#178 ✨ feat : interceptor 추가
  server/src/main/java/main027/server/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/main027/server/domain/bookmark/entity/Bookmark.java
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/place/controller/LikeController.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/repository/ReviewRepository.java
  server/src/main/java/main027/server/global/aop/logging/DataHolder.java
  server/src/main/java/main027/server/global/aop/logging/MemberHolder.java
  server/src/main/java/main027/server/global/aop/logging/aspect/TimeTraceAspect.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/config/InterceptorConfig.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/main/java/main027/server/global/interceptor/DataInterceptor.java
  server/src/test/java/main027/server/global/logging/TimeTraceTest.java
Labels: 🌕 BE, 💡 새기능, 🎨 리팩토링

#180 feat: 공통 모듈 및 장소상세보기 기능추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/api/place.js
  client/src/api/review.js
  client/src/components/Button/KakaoShareBtn.js
  client/src/components/Header/Header.js
  client/src/components/InfoModal/AboutEditForm.js
  client/src/components/InfoModal/LocationMap.js
  client/src/components/InfoModal/ReviewAddForm.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/UpvoteReport.js
  client/src/components/InfoModal/index.js
  client/src/components/Loading/Loading.js
  client/src/components/Map/StaticMap.js
  client/src/hooks/useFetch.js
  client/src/hooks/useMoveScroll.js
  client/src/hooks/useToastPopup.js
  client/src/index.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/pages/Mypage.js
  client/src/pages/NotFound.js
  client/src/query/index.js
  client/src/query/place.js
  client/src/query/review.js
  client/src/store/state/toastPopupState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/common.js
  client/src/utils/const.js
  client/src/utils/customAxios.js
Labels: ☀️ FE, 💡 새기능, 💄 스타일

#182 ✨ feat : map, place, list, tag 삼항연산자 구현
  .DS_Store
  client/package.json
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/Map.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/Home.js
  client/src/pages/Place.js
  client/src/recoil/atoms.js
Labels: ☀️ FE, 💡 새기능

#183 ✅ test : Member/Place Controller Test Code 수정
  server/src/main/java/main027/server/domain/member/controller/MemberController.java
  server/src/main/java/main027/server/domain/member/service/MemberService.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/main027/server/global/logging/TimeTraceTest.java
Labels: 🌕 BE, ✅ 테스트, 🔨 수정

#184 🔨 chore : 로깅 기능 추가 및 interceptor 활성화
  server/src/main/java/main027/server/global/aop/logging/DataHolder.java
  server/src/main/java/main027/server/global/aop/logging/aspect/TimeTraceAspect.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/config/InterceptorConfig.java
  server/src/main/java/main027/server/global/interceptor/DataInterceptor.java
Labels: 🌕 BE, 🔨 수정

#185 ✨ feat : review remove 구현 및 Exception 추가
  server/src/main/java/main027/server/domain/review/controller/ReviewController.java
  server/src/main/java/main027/server/domain/review/service/ReviewService.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/main/java/main027/server/global/advice/exception/PermissionDeniedException.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 💡 새기능

#186 chore : USER 접근 권한 수정
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
Labels: 🌕 BE, 🔨 수정

#189 🔨 chore : dataHolder memberId 적용
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateService.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 🔨 수정

#192 ✅ test : member/ review stub data 추가
  server/src/main/resources/sql/data.sql
Labels: 🌕 BE

#193 chore : MemberStatus 삭제 / 회원가입 시 중복 체크 수정
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/entity/Member.java
  server/src/main/java/main027/server/domain/member/repository/MemberRepository.java
  server/src/main/java/main027/server/domain/member/service/MemberServiceImpl.java
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/test/java/main027/server/domain/member/controller/MemberControllerTest.java
Labels: 🌕 BE, 🔨 수정

#195 hotfix: 장소 상세 보기 기능 및 공통 모듈 수정
  .github/workflows/client-test.yml
  .github/workflows/client.yml
  client/package.json
  client/src/api/place.js
  client/src/api/review.js
  client/src/components/Button/KakaoShareBtn.js
  client/src/components/InfoModal/AboutEditForm.js
  client/src/components/InfoModal/LocationMap.js
  client/src/components/InfoModal/ReviewAddForm.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/UpvoteReport.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/query/index.js
  client/src/query/place.js
  client/src/query/review.js
  client/src/utils/const.js
  client/src/utils/customAxios.js
Labels: ☀️ FE, 🔧 버그 수정, 👷 빌드 수정, 🚚 배포 관련

#197 chore : MemberStatus 삭제 / 회원가입 시 중복 체크 수정
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
  server/src/main/java/main027/server/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/main027/server/global/advice/dto/ErrorResponse.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
  server/src/main/java/main027/server/global/advice/exception/TokenException.java
  server/src/main/java/main027/server/global/auth/Redis/RedisService.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtReissueFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
Labels: 🌕 BE, 🔨 수정

#198 chore : ErrorResponder 수정
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
Labels: 🌕 BE, 🔧 버그 수정

#199 ✨ feat : 좋아요 숫자 기능 추가
  server/src/main/java/main027/server/domain/place/controller/LikeController.java
  server/src/main/java/main027/server/domain/place/dto/LikeDto.java
  server/src/main/java/main027/server/domain/place/repository/PlaceLikeUserRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeService.java
  server/src/main/java/main027/server/domain/place/service/PlaceLikeServiceImpl.java
Labels: 🌕 BE, 💡 새기능

#200 chore : cause 삭제
  server/src/main/java/main027/server/global/advice/dto/ErrorResponse.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationFailureHandler.java
Labels: 🌕 BE, 🔨 수정

#203 test : 액세스, 리프래쉬 토큰 생성 및 검증 테스트 / JWT 주석 수정
  server/src/main/java/main027/server/global/auth/Redis/RedisService.java
  server/src/main/java/main027/server/global/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/main027/server/global/auth/filter/JwtVerificationFilter.java
  server/src/main/java/main027/server/global/auth/jwt/JwtTokenizer.java
  server/src/main/java/main027/server/global/auth/userdetails/MemberDetailsService.java
  server/src/main/java/main027/server/global/auth/utils/ErrorResponder.java
  server/src/test/java/main027/server/global/auth/jwt/JwtTokenizerTest.java
Labels: 🌕 BE, ✅ 테스트, 🔨 수정

#204 ✅ test : RestDocs 작성 완료
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/test/java/main027/server/domain/bookmark/controller/BookmarkControllerTest.java
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/main027/server/domain/bookmark/service/BookmarkServiceTest.java
  server/src/test/java/main027/server/domain/place/LikeControllerTest.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/review/controller/ReviewControllerTest.java
  server/src/test/java/main027/server/domain/review/repository/ReviewRepositoryTest.java
  server/src/test/java/main027/server/global/logging/TimeTraceTest.java
Labels: 🌕 BE, ✅ 테스트

#205 ✨ feat : Place 검색 기능 추가
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
  server/src/main/java/main027/server/domain/place/service/PlaceService.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/global/advice/exception/ExceptionCode.java
Labels: 🌕 BE, 💡 새기능

#206 ✅ test : Place 검색 기능 추가 및 Restdocs 작성 완료
  server/src/docs/asciidoc/index.adoc
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, ✅ 테스트

#207 chore : nickname 숫자 가능 추가
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
Labels: 🌕 BE, 🔨 수정

#208 chore : patchMember 비밀번호 암호화
  server/src/main/java/main027/server/domain/member/service/MemberUpdateServiceImpl.java
Labels: 🌕 BE, 🔨 수정

#209 chore : @EntityGraph를 이용하여 장소 전체조회 쿼리 하나로 줄임
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/domain/place/repository/PlaceRepository.java
Labels: 🌕 BE, 🔨 수정

#210 🔨 chore : Logout Test
  client/src/api/login.js
  client/src/components/Header/Header.js
  client/src/components/Sign/Register.js
  client/src/pages/SignIn.js
  client/src/utils/customAxios.js
Labels: ☀️ FE, ✅ 테스트

#211 ✨ feat : Login, Home 화면 상세화면 연결 및 리스트 상세아이콘 수정
  client/src/App.js
  client/src/api/place.js
  client/src/assets/arrow+up+right.png
  client/src/assets/arrowUpRight.svg
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/MainMap copy.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/AddPlaceModal/AddPlaceModal.js
  client/src/pages/AddPlaceModal/AddPlaceModalStyle.js
  client/src/pages/Home.js
  client/src/pages/NotFound.js
  client/src/query/place.js
  client/src/recoil/atoms.js
Labels: ☀️ FE, 🎨 리팩토링

#214 chore: log 변경
  server/src/main/java/main027/server/global/aop/logging/DataHolder.java
Labels: 🌕 BE, 🔨 수정

#216 👷 build : 빌드 관련 파일 수정
  .github/workflows/client-test.yml
  .github/workflows/client.yml
  client/package.json
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
Labels: ☀️ FE, ✅ 테스트, 🚚 배포 관련

#215 💄 style : SiteInfoCard 수정
  client/src/components/Map/MainMap.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/Home.js
Labels: ☀️ FE, 💄 스타일

#219 feat: getPlaces Redis Cache Server 적용
  server/src/main/java/main027/server/ServerApplication.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/global/auth/Redis/RedisConfiguration.java
Labels: 🌕 BE, 💡 새기능

#220 ✨ feat : 로그인 시 유저 환영인사 추가
  client/src/assets/emoji/ico-01-happy.svg
  client/src/assets/emoji/ico-02-concern.svg
  client/src/assets/emoji/ico-03-smile.svg
  client/src/assets/emoji/ico-04-crazy-love.svg
  client/src/assets/emoji/ico-05-unhappy.svg
  client/src/assets/emoji/ico-06-satisfaction.svg
  client/src/assets/emoji/ico-07-pleading.svg
  client/src/assets/emoji/ico-08-anguished.svg
  client/src/assets/emoji/ico-09-relieved-laughter.svg
  client/src/assets/emoji/ico-10-persevere.svg
  client/src/components/Header/Header.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/components/Sign/Register.js
Labels: ☀️ FE, 💡 새기능, 🔨 수정

#221 ✨ feat : 카테고리별 리스트 기능 구현
  client/package.json
  client/src/api/place.js
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/pages/Home.js
  client/src/query/place.js
  client/src/recoil/atoms.js
Labels: ☀️ FE, 💡 새기능, 🔧 버그 수정

#223 chore : 로그인 시 닉네임 응답값 수정
  server/src/main/java/main027/server/ServerApplication.java
  server/src/main/java/main027/server/domain/place/controller/PlaceController.java
  server/src/main/java/main027/server/domain/place/entity/Place.java
  server/src/main/java/main027/server/global/auth/Redis/RedisConfiguration.java
  server/src/main/java/main027/server/global/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: 🌕 BE, 🔧 버그 수정

#224 ✨ feat: 엑세스 토큰 재발급 기능 추가 및 수정보완
  client/package.json
  client/src/App.js
  client/src/api/bookmark.js
  client/src/api/like.js
  client/src/api/login.js
  client/src/api/member.js
  client/src/api/review.js
  client/src/assets/emoji/index.js
  client/src/components/Button/KakaoShareBtn.js
  client/src/components/Header/Header.js
  client/src/components/InfoModal/ReviewAddForm.js
  client/src/components/InfoModal/ReviewAddFormStyle.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ReviewListStyle.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/TitleStyle.js
  client/src/components/InfoModal/UpvoteReport.js
  client/src/components/Sign/Register.js
  client/src/index.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/pages/Mypage/MyInfo.js
  client/src/pages/Mypage/PwdEditFormModal.js
  client/src/pages/PlaceInfo.js
  client/src/pages/SignIn.js
  client/src/query/review.js
  client/src/recoil/reviewState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/const.js
  client/src/utils/customAxios.js
Labels: ☀️ FE, 💡 새기능, 🔨 수정

#225 ✨ feat : 추가 기능 보완 - 2차 완료 배포
  client/package.json
  client/src/App.js
  client/src/api/bookmark.js
  client/src/api/like.js
  client/src/api/login.js
  client/src/api/member.js
  client/src/api/place.js
  client/src/api/review.js
  client/src/assets/emoji/ico-01-happy.svg
  client/src/assets/emoji/ico-02-concern.svg
  client/src/assets/emoji/ico-03-smile.svg
  client/src/assets/emoji/ico-04-crazy-love.svg
  client/src/assets/emoji/ico-05-unhappy.svg
  client/src/assets/emoji/ico-06-satisfaction.svg
  client/src/assets/emoji/ico-07-pleading.svg
  client/src/assets/emoji/ico-08-anguished.svg
  client/src/assets/emoji/ico-09-relieved-laughter.svg
  client/src/assets/emoji/ico-10-persevere.svg
  client/src/assets/emoji/index.js
  client/src/components/Button/KakaoShareBtn.js
  client/src/components/Header/Header.js
  client/src/components/InfoModal/ReviewAddForm.js
  client/src/components/InfoModal/ReviewAddFormStyle.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ReviewListStyle.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/TitleStyle.js
  client/src/components/InfoModal/UpvoteReport.js
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/RadioButton.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/components/Sign/Register.js
  client/src/index.js
  client/src/pages/Home.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/InfoModal/InfoModalStyle.js
  client/src/pages/Mypage/MyInfo.js
  client/src/pages/Mypage/PwdEditFormModal.js
  client/src/pages/PlaceInfo.js
  client/src/pages/SignIn.js
  client/src/query/place.js
  client/src/query/review.js
  client/src/recoil/atoms.js
  client/src/recoil/reviewState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/const.js
  client/src/utils/customAxios.js
Labels: ☀️ FE, 💡 새기능, 🔧 버그 수정, 🔨 수정, 🚚 배포 관련

#226 💄 style : favicon 추가
  client/public/favicon.ico
Labels: ☀️ FE, 💄 스타일

#228 💄 style : thumbnail 추가
  client/public/thumbnail.png
Labels: ☀️ FE, 💄 스타일

#227 💄 style: 파비콘 추가
  client/public/favicon.ico
  client/public/thumbnail.png
  client/src/components/Button/KakaoShareBtn.js
Labels: ☀️ FE, 💄 스타일

#229 🔨 chore : Sign err msg 수정
  client/src/components/Sign/Register.js
  client/src/pages/SignIn.js
Labels: ☀️ FE, 💄 스타일

#230 chore : 장소 검색 시 응답값에 위도, 경도 추가
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 🔨 수정

#232 Backend
  server/src/main/java/main027/server/domain/place/dto/PlaceDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/test/java/main027/server/domain/place/PlaceControllerTest.java
Labels: 🌕 BE, 🔨 수정

#233 ✨ feat : 검색 기능 구현 완료
  .DS_Store
  client/src/api/place.js
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/query/place.js
  client/src/utils/const.js
Labels: ☀️ FE, 💡 새기능, 🔧 버그 수정

#234 test : MemberRepositoryTest 추가
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/test/java/main027/server/domain/member/repository/MemberRepositoryTest.java
Labels: 🌕 BE, ✅ 테스트

#235 chore : RedisConfiguration 위치 변경
  server/src/main/java/main027/server/global/config/RedisConfiguration.java
Labels: 🌕 BE, 🔨 수정

#236 chore : 비밀번호 조합 변경.
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
Labels: 🌕 BE, 🔨 수정

#237 이것저것
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/member/verifier/MemberVerifier.java
  server/src/main/java/main027/server/global/config/RedisConfiguration.java
  server/src/test/java/main027/server/domain/member/repository/MemberRepositoryTest.java
Labels: 🌕 BE

#240 ✨ feat : 서비스 소개 추가
  client/src/App.js
  client/src/pages/AboutUs.js
  client/src/pages/AboutUs/AboutUs.js
  client/src/pages/AboutUs/TabAboutUs.js
Labels: ☀️ FE

#239 🔨 chore : list category address 오류 수정
  client/src/api/place.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/Home.js
  client/src/query/place.js
Labels: ☀️ FE, 💡 새기능, 🔧 버그 수정, 🎨 리팩토링

#241 ✨ feat: 오류 제보 기능 추가 및 수정
  client/src/App.js
  client/src/api/like.js
  client/src/api/mail.js
  client/src/api/review.js
  client/src/components/Header/Header.js
  client/src/components/InfoModal/ReviewList.js
  client/src/components/InfoModal/ShareBookmark.js
  client/src/components/InfoModal/Title.js
  client/src/components/InfoModal/UpvoteReport.js
  client/src/components/Nav/Nav.js
  client/src/components/Sign/Register.js
  client/src/pages/InfoModal/InfoModal.js
  client/src/pages/Mypage/Like.js
  client/src/pages/Mypage/LikeStyle.js
  client/src/pages/Mypage/Mypage.js
  client/src/pages/Mypage/PwdEditFormModal.js
  client/src/pages/Report/ReportModal.js
  client/src/pages/Report/ReportModalStyle.js
  client/src/pages/SignIn.js
  client/src/query/like.js
  client/src/recoil/modalState.js
  client/src/styles/GlobalStyle.js
  client/src/utils/common.js
  client/src/utils/const.js
Labels: ☀️ FE, 💡 새기능, 🔧 버그 수정, 🔨 수정

#245 🔨 chore : 충돌 수정 및 주석제거
  client/package.json
  client/src/api/place.js
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/pages/AddPlaceModal/AddPlaceModalStyle.js
Labels: ☀️ FE

#247 💄 style : Nav, 장소등록 Btn 수정
  client/src/components/Map/MainMap.js
  client/src/components/Nav/Nav.js
Labels: ☀️ FE

#249 💄 style : 장소등록 Btn 수정 re
  client/src/components/Map/MainMap.js
Labels: ☀️ FE

#250 🔨 chore : search reset btn
  client/src/components/Map/SearchBar/SearchBar.js
Labels: ☀️ FE, 🔨 수정

#253 ✅ test : Place Service Slice Test Code 작성
  server/build.gradle
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/main027/server/domain/place/controller/LikeControllerTest.java
  server/src/test/java/main027/server/domain/place/controller/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/place/repository/PlaceRepositoryTest.java
  server/src/test/java/main027/server/domain/place/service/PlaceServiceTest.java
Labels: 🌕 BE, ✅ 테스트

#251 test : memberService 테스트 코드
  server/src/test/java/main027/server/domain/member/service/MemberServiceImplTest.java
Labels: 🌕 BE, ✅ 테스트

#255 🐛 fix : 2023-1-30 version
  client/package.json
  client/src/api/place.js
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/MainMap.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/components/Nav/Nav.js
  client/src/pages/AddPlaceModal/AddPlaceModalStyle.js
Labels: ☀️ FE, 🚚 배포 관련

#256 🔨 chore : Sign err별 msg 수정
  client/src/components/Sign/Register.js
  client/src/pages/SignIn.js
Labels: ☀️ FE

#257 🔨 chore : list 주소 css 공백 기준 줄 바꿈, 버그 수정완료
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
Labels: ☀️ FE, 💄 스타일, 🔨 수정

#258 chore : 지도 list 주소 css 공백 기준 줄 바꿈, 버그 수정완료
  client/src/components/Map/AddPlaceInfo.js
  client/src/components/Map/CategorySelectBox.js
  client/src/components/Map/SearchBar/SearchBar.js
  client/src/components/Map/SearchBar/SelectBox.js
  client/src/components/Map/SiteInfoCard/SiteInfoCard.js
  client/src/components/Sign/Register.js
  client/src/pages/SignIn.js
Labels: ☀️ FE, 🔧 버그 수정, 🚚 배포 관련

#261 🔨 chore : search reset 수정
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/SearchBar/SearchInput.js
Labels: ☀️ FE, 🔧 버그 수정, 🔨 수정

#262 chore : search reset 수정
  client/src/components/Map/AddPlaceMap.js
  client/src/components/Map/SearchBar/SearchInput.js
  client/src/pages/AboutUs/AboutUs.js
Labels: ☀️ FE, 🚚 배포 관련

#263 📝 docs : Readme 추가
  README.md
Labels: 📝 문서 관련

#254 placeService & memberService Test Code 작성
  server/build.gradle
  server/src/main/generated/main027/server/domain/place/mapper/PlaceMapperImpl.java
  server/src/main/generated/main027/server/domain/review/mapper/ReviewMapperImpl.java
  server/src/main/java/main027/server/domain/member/dto/MemberDto.java
  server/src/main/java/main027/server/domain/place/mapper/PlaceMapper.java
  server/src/main/java/main027/server/domain/place/service/PlaceServiceImpl.java
  server/src/main/java/main027/server/domain/place/service/PlaceUpdateServiceImpl.java
  server/src/main/java/main027/server/domain/review/service/ReviewServiceImpl.java
  server/src/main/java/main027/server/global/config/SecurityConfiguration.java
  server/src/test/java/main027/server/domain/bookmark/repository/BookmarkRepositoryTest.java
  server/src/test/java/main027/server/domain/member/service/MemberServiceImplTest.java
  server/src/test/java/main027/server/domain/place/controller/LikeControllerTest.java
  server/src/test/java/main027/server/domain/place/controller/PlaceControllerTest.java
  server/src/test/java/main027/server/domain/place/repository/PlaceRepositoryTest.java
  server/src/test/java/main027/server/domain/place/service/PlaceServiceTest.java
Labels: 🌕 BE, ✅ 테스트

#264 📝 docs : 이미지 및 뱃지 추가
  README.md
Labels: ☀️ FE
